FROM nginx:1.21.1-alpine

EXPOSE 80
EXPOSE 443

RUN apk add --no-cache openssl

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

WORKDIR /etc/nginx/ssl/

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
 -keyout nginx-selfsigned.key -out nginx-selfsigned.crt \
  -subj "/C=US/ST=Denial/L=Springfield/O=TON/CN=ton-drive"
