services:
  storage:
    build:
      dockerfile: ./Dockerfile.ton-storage
    ports:
      - "3333:3333"
      - "5555:5555"
    volumes:
      - .docker-volumes/ton-storage/:/usr/ton-storage/storage-db/:rw
      - .docker-volumes/upload:/usr/src/app/.upload/:ro
    networks:
      - web

  service:
    build:
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - .docker-volumes/ton-storage/:/usr/ton-storage/storage-db/:ro
      - .docker-volumes/upload/:/usr/src/app/.upload/:rw
    environment:
      TON_STORAGE_HOST: storage
      STORAGE_CLI_EXEC_PATH: ./storage-daemon-cli
      STORAGE_WORK_DIR: /usr/ton-storage/
      USE_SHELL: 'true'
    depends_on:
      - storage
    networks:
      - web

  nginx:
    build:
      dockerfile: ./Dockerfile.nginx
    restart: always
    ports:
      - "8051:80"
    logging:
      options:
        max-size: "100m"
        max-file: "100"
    env_file:
      - ./.env
    depends_on:
      - service
    networks:
      - web

networks:
  web:
    external: true #needs to be created by other file
    name: shared-web
